modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="dealmaker"
mandatory=true
versionRange="[0.1.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="knights_of_britannia"
mandatory=true
versionRange="[0.1.0,)"
ordering="AFTER"
side="BOTH"
